/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:25f3109c-834c-4142-9334-18265a3bb1eb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_orVvSEIQ6",
    "aws_user_pools_web_client_id": "22jr33lik7r0euihakfbfkuqvr",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsconfig;
